# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  exception:
    codes:
      'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
      'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
      'Doctrine\DBAL\Exception\UniqueConstraintViolationException': HTTP_CONFLICT
    messages: true
  param_fetcher_listener: true
  body_listener: true
  body_converter:
    enabled: true
  format_listener:
    enabled: true
    rules:
      - { path: "^/", priorities: [ "json" ], fallback_format: "html" }
  versioning: true
  view:
    view_response_listener: 'force'