###
POST https://127.0.0.1:8080/api/login_check
Content-Type: application/json

{"username": "onekit@gmail.com", "password": "admin"}

> {% client.global.set("auth_token", response.body.json.token); %}
###
GET http://127.0.0.1:8080/api/users
Authorization: Bearer {{auth_token}}
Accept: application/json

###
GET http://127.0.0.1:8080/api/users
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2MDI5MzI4NDksImV4cCI6MTYwMjkzNjQ0OSwicm9sZXMiOlsiUk9MRV9VU0VSIiwiUk9MRV9BRE1JTiJdLCJlbWFpbCI6Im9uZWtpdEBnbWFpbC5jb20ifQ.AmnbZapvQr-Vz8nDMZy1yRJ0xSnI_ZFgr2_wFxd1jT9_Pc19Af9_63vqV5W--3Q2meKlPmviZGaPkt1LLJ57BnWdoL3Fhyo9W6Nhs5zVtIyQn-u03hQrLAMbIh5D4ct8wbZBtTNFj8yLvtPve-7LXWpO2Lp6U8uTXy4WwhiRCpusMNTFFLaZszRNPGGoy1llswgvqNboV7ayHXIr1H6frekMrNsM9zbmA_Zing9bBHzA5XzWLKFJTpgJw62D0BJ34LIJB0n6N8o6azjSNRr-gFA8HYYNWFoG6jDW4AqbOWtxwal0a00IxyG9lTpekmikuABr68o3mEAc8QNT5es6u_f5Gf0_63y56hIVtCE2AXpHfxH2zo7QzjnBQZPsMxypkZXzQMzr2wjlY3Ft-nGkbv8kB2qci136ib7CqOxBmIRudyF3Z3DQvEfK3S9RTOJh7d3PaZ8rkmSXdSgfzpCpNkPKCflMP3Cw6Rv5Mj-nWBOpwjFoyio54BEjOiD6lPsTDA19-sGQRdPE2rTq0AnOC8C7Ohnd8hBaggOJWttFPOOkMg_nUaPHWrZ-HxM2oxiXajF42ZsVNGLcYk9Qb7ZtRVbFu8ocepEcj_5cG94T7DYQ0dofvN8CqWIm1KfTzIMLSOUHuhLOE2RT_fMbywRSUxT1fKfuyx3WpE_noDFI-50
Accept: application/json

###

GET http://127.0.0.1:8080/api/users/1
Authorization: Bearer {{auth_token}}
Accept: application/json

###
PUT https://127.0.0.1:8080/api/users/1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{auth_token}}

{
  "email": "onekit@1kit.net",
  "password": "admin",
  "firstName": "Alex",
  "lastName": "Smith",
  "phone": "+123456789"
}


###
POST https://127.0.0.1:8080/api/users
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2MDI5NDA2MTAsImV4cCI6MTYwMjk1NjIxMCwicm9sZXMiOlsiUk9MRV9VU0VSIiwiUk9MRV9BRE1JTiJdLCJlbWFpbCI6Im9uZWtpdEBnbWFpbC5jb20ifQ.D-VtwZNBEMC2Hab8qMatQFptkFgZdkpibvrzbfgupigXf4E_pUK_EXc_Z1ATnRg1jXEqGKcEayC7St248e8qXnlZrVJokKGkAA2zb6ed4au9XC6V8mREYg3GVH8VR_3MIFK4xju2CTnUt84phvF6jXN9Pbe_vQyGClQKWg_YKyS1FY95ckHPtdRyUye1SH7VAHzu2WkI9Blk2cPXQgYwCpI6bIPIccU-mnZEL9WRJN3f7koLM8yXFRtlCc_7TqbGccnbnpnHqeSKJe0L_Sw4wzEogey3qNHO65lb1d5uDeOOIKosx7Ewpcx1KVhfW3ViuZuuZ0XD-_VVW4pIM39hmS8e6rlI2UaTyD6aVj2nEYruL4l1r8w3rqbSOefV6CjBOtpAyIL9IK7cXM_boECblPXvPds9WmACHKpffP2xYWLsfQs0_YNAwzrjEpewQGqL3wFoZ71RKBIxto7fFPihYJwM7Kh41WXCIUR5APf1vH8uNvGS02wQfNy-vPvUh8Pc3YcQWeKZv2LMsWb-4z6aZTPWDxSrknyi4n-DZ6CRycZDXnMsqJLX2c3W57_VYG4jOqc91YuM3rU1Ar3GYOYZiCyXbx57Jc2lkcwpUvjxCoPF_ld3JsWZcSTCaMmRc2_vD1Cp033TZVGyJdBLAPkvBtX4jGxUW90UZrorqRZUJ6w

{
  "email": "alexa@asdsgggmmmmf.com",
  "firstName": "g",
  "lastName": "S",
  "phone": "",
  "password": "admin"
}


###


###
PUT https://127.0.0.1:8080/api/users/78
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2MDI5MzI4NDksImV4cCI6MTYwMjkzNjQ0OSwicm9sZXMiOlsiUk9MRV9VU0VSIiwiUk9MRV9BRE1JTiJdLCJlbWFpbCI6Im9uZWtpdEBnbWFpbC5jb20ifQ.AmnbZapvQr-Vz8nDMZy1yRJ0xSnI_ZFgr2_wFxd1jT9_Pc19Af9_63vqV5W--3Q2meKlPmviZGaPkt1LLJ57BnWdoL3Fhyo9W6Nhs5zVtIyQn-u03hQrLAMbIh5D4ct8wbZBtTNFj8yLvtPve-7LXWpO2Lp6U8uTXy4WwhiRCpusMNTFFLaZszRNPGGoy1llswgvqNboV7ayHXIr1H6frekMrNsM9zbmA_Zing9bBHzA5XzWLKFJTpgJw62D0BJ34LIJB0n6N8o6azjSNRr-gFA8HYYNWFoG6jDW4AqbOWtxwal0a00IxyG9lTpekmikuABr68o3mEAc8QNT5es6u_f5Gf0_63y56hIVtCE2AXpHfxH2zo7QzjnBQZPsMxypkZXzQMzr2wjlY3Ft-nGkbv8kB2qci136ib7CqOxBmIRudyF3Z3DQvEfK3S9RTOJh7d3PaZ8rkmSXdSgfzpCpNkPKCflMP3Cw6Rv5Mj-nWBOpwjFoyio54BEjOiD6lPsTDA19-sGQRdPE2rTq0AnOC8C7Ohnd8hBaggOJWttFPOOkMg_nUaPHWrZ-HxM2oxiXajF42ZsVNGLcYk9Qb7ZtRVbFu8ocepEcj_5cG94T7DYQ0dofvN8CqWIm1KfTzIMLSOUHuhLOE2RT_fMbywRSUxT1fKfuyx3WpE_noDFI-50

{
  "email": "one2ei3t@1kit.sax",
  "firstName": "A",
  "lastName": "S",
  "phone": "+123412356789",
  "password": "asdmin"
}


###


###
DELETE https://127.0.0.1:8080/api/users/35
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2MDI4ODgwMDgsImV4cCI6MTYwMjg5MTYwOCwicm9sZXMiOlsiUk9MRV9VU0VSIiwiUk9MRV9BRE1JTiJdLCJlbWFpbCI6Im9uZWtpdEBnbWFpbC5jb20ifQ.312ROYsDCD456NrqpZVN7BATXOA4LW6Bi1vq8pkFylPGzH_V-SNQF_P1oLQ2TVZDk18j8xf6JxHYggP1FMj2H2hT0FXEKGInyxhepGyC2sqnsVjmrsNvBwbDFp93tl5ZwM3JvmT_Zr0iIBMErLALyetUbkulL2f5hTgrF1PmqGOv02WuLyGuHafDkvHCh4WwRmZ4HmaIF3xmecUXDgh37oHE54tn7VKTSbxy3GL3tMjnt-M42T5H-mcaP77womfZIo9qSBliWaXRKmT0rKrVC7yhN0g0_0Z53zWdwIGK54y8Ht-jVReJn-FSNtnJcZd5xeNGwyATfZzpNEdwbquQzfjBdvthg61z08C5LeHo93PHycbgKCA3s_G_vDOOR2fIWi6Xv-x6GGzKJmGQs078NQgy--B8aTTvC869pAQl83dT7o8EuhSa-Qj6bH8RxbOFLA2fHaKwhLDxyJvc_SRvgpzEXuoo9YIoGldjr2bhIVbTObcDsYd3Da1bXOcQcsIJVHjtUmylzehH2MRpRN8uHtQ0AxU_yFEA5NzNouv9ldlWL8_9ce4kSgbp6mHycE4TiWy4pvHCxYpGG3D0BQmyqq-cRx7Iwn-vorqyrSCVIoTVC_Ow0ajaxWo4FGQz8kqo6DO66YydUhpfbqKmp-1I8FHNYkjwqMtm6i2p6g-lKXk
###
