GET http://127.0.0.1:8001/api/users
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2MDI4NjAwOTAsImV4cCI6MTYwMjg2MzY5MCwicm9sZXMiOlsiUk9MRV9VU0VSIiwiUk9MRV9BRE1JTiJdLCJlbWFpbCI6Im9uZWtpdEBnbWFpbC5jb20ifQ.Gil3i3KqGMw9ZO8_L_wg7iqRuw4Sg1UlyQBWBVZgoLP72OoKYlWRayH7m6IVtOgOx0Ay5reL1fu4l604cxLY6kYwCP9Lm82of7mMeEbEWUwQpPglps72UN0gO7d91rlN0Vb-rNJulvNbo8VK9WonhyJDUvKy41xMX6Mi_7s361IqHa-na14-kozFXU8Sm6FZOLkCXRO_qIjzFfRjzLuFr7DOTc71jiPXHZ3oASFKGNw3jdLCrDK1S2K4jx6QJ9n5KbrXE5zh8zdIZWiYAFba3J0Vsrbd8_lgx-6Bl1RlcQWVgkzh4gmKTwQwOnLuBpDYEkIjclwOW48IBHpcFKIcYckt3Tx0ZvSKfitPfKq_uBQy0xMFn4y7LDGz0RVZr24SoUxfqA8McrCxJ0B2-nejIdPEOhilAdn6_GUV6Ew7UI8tjU7_ET1og5erFteN23JqhujLAefSx35B6e116K5LoazZNmtdQNRZ02OpPNgiP4672HVWB94Lk3EmW3Jv3rgQJA0wlTYqICqmsRI9VlR9adBwwA5NCZKgt9tv1bFxO_dveitKIf78ZB0AzM9UHzBiODnvQ42axTvcc3VxvrNoviDV16xcxESIKfrImKZlgsyLNsMYJhyridtf-ctnJh6fl3sq_AIoiauecxL4jae45irPkNydxfMAVD93ZeyGJo0
Accept: application/json

###
POST https://127.0.0.1:8001/api/users
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2MDI4NjAwOTAsImV4cCI6MTYwMjg2MzY5MCwicm9sZXMiOlsiUk9MRV9VU0VSIiwiUk9MRV9BRE1JTiJdLCJlbWFpbCI6Im9uZWtpdEBnbWFpbC5jb20ifQ.Gil3i3KqGMw9ZO8_L_wg7iqRuw4Sg1UlyQBWBVZgoLP72OoKYlWRayH7m6IVtOgOx0Ay5reL1fu4l604cxLY6kYwCP9Lm82of7mMeEbEWUwQpPglps72UN0gO7d91rlN0Vb-rNJulvNbo8VK9WonhyJDUvKy41xMX6Mi_7s361IqHa-na14-kozFXU8Sm6FZOLkCXRO_qIjzFfRjzLuFr7DOTc71jiPXHZ3oASFKGNw3jdLCrDK1S2K4jx6QJ9n5KbrXE5zh8zdIZWiYAFba3J0Vsrbd8_lgx-6Bl1RlcQWVgkzh4gmKTwQwOnLuBpDYEkIjclwOW48IBHpcFKIcYckt3Tx0ZvSKfitPfKq_uBQy0xMFn4y7LDGz0RVZr24SoUxfqA8McrCxJ0B2-nejIdPEOhilAdn6_GUV6Ew7UI8tjU7_ET1og5erFteN23JqhujLAefSx35B6e116K5LoazZNmtdQNRZ02OpPNgiP4672HVWB94Lk3EmW3Jv3rgQJA0wlTYqICqmsRI9VlR9adBwwA5NCZKgt9tv1bFxO_dveitKIf78ZB0AzM9UHzBiODnvQ42axTvcc3VxvrNoviDV16xcxESIKfrImKZlgsyLNsMYJhyridtf-ctnJh6fl3sq_AIoiauecxL4jae45irPkNydxfMAVD93ZeyGJo0

{"username": "onekit@1kit.net", "password": "admin"}


###
POST https://127.0.0.1:8001/api/login_check
Content-Type: application/json

{"username": "onekit@gmail.com", "password": "admin"}


###