###
POST https://127.0.0.1:8080/api/login_check
Content-Type: application/json

{"username": "onekit@gmail.com", "password": "admin"}
> {%
    client.global.set("auth_token", response.body.token);
%}
###
GET http://127.0.0.1:8080/api/users
Authorization: Bearer {{auth_token}}
Accept: application/json

> {%
    client.global.set("user_id", response.body[0].id);
%}
###

GET http://127.0.0.1:8080/api/users/{{user_id}}
Authorization: Bearer {{auth_token}}
Accept: application/json

###

PUT https://127.0.0.1:8080/api/users/{{user_id}}
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{auth_token}}

{
  "email": "onekit@gmail.com",
  "password": "admin",
  "firstName": "Alex",
  "lastName": "Test",
  "phone": "+375292193504"
}

###

POST https://127.0.0.1:8080/api/users
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{auth_token}}

> {%
    client.global.set("new_id", response.body.id);
%}
###

PUT https://127.0.0.1:8080/api/users/{{new_id}}
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{auth_token}}

{
  "email": "onekit@2gmail.com",
  "firstName": "Alexander",
  "lastName": "Schumann",
  "phone": "+375292193504",
  "password": "admin"
}

###

DELETE https://127.0.0.1:8080/api/users/{{new_id}}
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{auth_token}}
###
