default:
    path: /
    controller: App\Controller\DefaultController::index

api_login_check:
  path: /api/login_check

api_routes:
  resource: "../src/Controller/Api"
  type: annotation
  prefix: /api
  defaults: { _format: json }
