default:
    path: /
    controller: App\Controller\DefaultController::index

api_login_check:
  path: /api/login_check
  defaults: { _format: json }

api_routes:
  resource: "../src/Controller/Api"
  type: annotation
  prefix: /api
  defaults: { _format: json }

app.swagger_ui:
  path: /api/doc
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

app.swagger:
  path: /api/doc.json
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger }